const STORE='afd-simple-content-queue-v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let queue=JSON.parse(localStorage.getItem(STORE)||'[]'),image='';
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function clean(text=''){return text.replace(/[.!?]+$/,'').trim()}
function makePost(topic,goal,brand,voice,cta){const idea=clean(topic);const hooks={awareness:`DJs: ${idea}—without losing what makes you original.`,traffic:`If ${idea.toLowerCase()} matters to your DJ business, start here.`,sales:'Stop rebuilding the same business work every week.',education:`Here is a practical way to think about ${idea.toLowerCase()}.`};const hook=hooks[goal];const caption=`${hook}\n\nAI should handle repetitive preparation—not replace your taste, crowd reading or creativity.\n\nUse it for research, planning, writing and organization. Then bring your own experience to the final decision.\n\n${cta}`;return{brand,topic,caption,hashtags:'#AIForDJs #DJBusiness #WorkingDJ #DJTools #MusicTechnology',script:`${hook}\n\nMost DJs do not need more hype. They need a faster way to handle the work around the music.\n\nAI can help with research, planning, writing and organization. But the DJ still makes the creative decision.\n\n${cta}`,visual:`Use an authentic ${brand} picture connected to “${idea}.” Keep the DJ equipment accurate and the layout clean.`,voice,image,created:new Date().toISOString()}}
$('#contentForm').onsubmit=e=>{e.preventDefault();const post=makePost($('#topic').value,$('#goal').value,$('#brandSelect').value,$('#voice').value,$('#cta').value);$('#captionOut').value=post.caption;$('#hashtagsOut').value=post.hashtags;$('#scriptOut').value=post.script;$('#visualOut').value=post.visual;const img=$('#mediaPreview');if(image){img.src=image;img.hidden=false}else img.hidden=true;$('#resultCard').hidden=false;$('#resultCard').scrollIntoView({behavior:'smooth',block:'start'});toast('Post created')};
$('#mediaInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{image=reader.result;$('#photoLabel').textContent=file.name;toast('Picture added')};reader.readAsDataURL(file)};
function current(){return{brand:$('#brandSelect').value,topic:$('#topic').value,caption:$('#captionOut').value,hashtags:$('#hashtagsOut').value,script:$('#scriptOut').value,visual:$('#visualOut').value,image,created:new Date().toISOString()}}
$('#copyPack').onclick=async()=>{const p=current();await navigator.clipboard.writeText(`${p.caption}\n\n${p.hashtags}`);toast('Copied for Blotato')};
$('#addQueue').onclick=()=>{if(queue.length===5)queue.shift();queue.push(current());localStorage.setItem(STORE,JSON.stringify(queue));render();toast('Saved to queue')};
function render(){const grid=$('#queueGrid');$('#queueCount').textContent=queue.length;if(!queue.length){grid.innerHTML='<div class="queue-empty">No posts saved yet. Create one, review it, then save it here.</div>';return}const start=new Date();grid.innerHTML=queue.map((p,i)=>{const day=new Date(start);day.setDate(start.getDate()+i);return `<article class="queue-item"><div class="queue-day">${day.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}).toUpperCase()}<br>10:00 AM</div><div class="queue-copy"><h3>${p.brand}</h3><p>${p.caption}</p></div><button class="button secondary copy" data-i="${i}">Copy</button></article>`}).join('');$$('.copy').forEach(b=>b.onclick=async()=>{const p=queue[+b.dataset.i];await navigator.clipboard.writeText(`${p.caption}\n\n${p.hashtags}`);toast('Post copied')})}
$$('.tab').forEach(tab=>tab.onclick=()=>{$$('.tab,.view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#view-${tab.dataset.view}`).classList.add('active')});
$('#downloadAll').onclick=()=>{if(!queue.length)return toast('Queue is empty');const text=queue.map((p,i)=>`DAY ${i+1} — 10:00 AM\n${p.caption}\n\n${p.hashtags}`).join('\n\n--------------------\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='five-day-content-queue.txt';a.click();URL.revokeObjectURL(url);toast('Queue downloaded')};
render();
